version: '3'

services:
  api:
    restart: always
    image: openfoodfacts/robotoff
    network_mode: "host"
    volumes:
      - api-dataset:/opt/robotoff/datasets
      - ./tf_models:/opt/robotoff/tf_models:Z
      - ./models:/opt/robotoff/models:Z
    mem_limit: 2g
    ports:
      - "5500:5500"

  postgres:
    restart: always
    image: postgres:11.2-alpine
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    mem_limit: 2g

volumes:
  postgres-data:
  api-dataset:
